In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
data=pd.read_csv("Combined.csv")
data.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15674932,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,1.0,0.0,181449.97,0
1,1,15749177,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,1.0,1.0,49503.50,0
2,2,15694510,Hsueh,678,France,Male,40.0,10,0.00,2,1.0,0.0,184866.69,0
3,3,15741417,Kao,581,France,Male,34.0,2,148882.54,1,1.0,1.0,84560.88,0
4,4,15766172,Chiemenam,716,Spain,Male,33.0,5,0.00,2,1.0,1.0,15068.83,0

In [3]:
data=data.drop(["id","CustomerId"],axis=1)
data

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Okwudilichukwu,668,France,Male,33.0,3,0.00,2,1.0,0.0,181449.97,0
1,Okwudiliolisa,627,France,Male,33.0,1,0.00,2,1.0,1.0,49503.50,0
2,Hsueh,678,France,Male,40.0,10,0.00,2,1.0,0.0,184866.69,0
3,Kao,581,France,Male,34.0,2,148882.54,1,1.0,1.0,84560.88,0
4,Chiemenam,716,Spain,Male,33.0,5,0.00,2,1.0,1.0,15068.83,0
...,...,...,...,...,...,...,...,...,...,...,...,...
175027,Liu,709,France,Female,36.0,7,0.00,1,0.0,1.0,42085.58,1
175028,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
175029,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1.0,0.0,92888.52,1
175030,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0
175031,Walker,792,France,Female,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [4]:
data["Age"]=data["Age"].astype(int)

In [5]:
data

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Okwudilichukwu,668,France,Male,33,3,0.00,2,1.0,0.0,181449.97,0
1,Okwudiliolisa,627,France,Male,33,1,0.00,2,1.0,1.0,49503.50,0
2,Hsueh,678,France,Male,40,10,0.00,2,1.0,0.0,184866.69,0
3,Kao,581,France,Male,34,2,148882.54,1,1.0,1.0,84560.88,0
4,Chiemenam,716,Spain,Male,33,5,0.00,2,1.0,1.0,15068.83,0
...,...,...,...,...,...,...,...,...,...,...,...,...
175027,Liu,709,France,Female,36,7,0.00,1,0.0,1.0,42085.58,1
175028,Sabbatini,772,Germany,Male,42,3,75075.31,2,1.0,0.0,92888.52,1
175029,Sabbatini,772,Germany,Male,42,3,75075.31,2,1.0,0.0,92888.52,1
175030,Walker,792,France,Female,28,4,130142.79,1,1.0,0.0,38190.78,0
175031,Walker,792,France,Female,28,4,130142.79,1,1.0,0.0,38190.78,0

In [6]:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])

In [7]:
data

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Okwudilichukwu,668,France,1,33,3,0.00,2,1.0,0.0,181449.97,0
1,Okwudiliolisa,627,France,1,33,1,0.00,2,1.0,1.0,49503.50,0
2,Hsueh,678,France,1,40,10,0.00,2,1.0,0.0,184866.69,0
3,Kao,581,France,1,34,2,148882.54,1,1.0,1.0,84560.88,0
4,Chiemenam,716,Spain,1,33,5,0.00,2,1.0,1.0,15068.83,0
...,...,...,...,...,...,...,...,...,...,...,...,...
175027,Liu,709,France,0,36,7,0.00,1,0.0,1.0,42085.58,1
175028,Sabbatini,772,Germany,1,42,3,75075.31,2,1.0,0.0,92888.52,1
175029,Sabbatini,772,Germany,1,42,3,75075.31,2,1.0,0.0,92888.52,1
175030,Walker,792,France,0,28,4,130142.79,1,1.0,0.0,38190.78,0
175031,Walker,792,France,0,28,4,130142.79,1,1.0,0.0,38190.78,0

In [8]:
# using OneHotEncode for Geography column
from sklearn.preprocessing import OneHotEncoder
onehot_geo=OneHotEncoder(sparse_output=False)

In [9]:
geo_encoder=onehot_geo.fit_transform(data[["Geography"]])
geo_encoder

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], shape=(175032, 3))

In [10]:
onehot_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_encoder_df=pd.DataFrame(geo_encoder,columns=onehot_geo.get_feature_names_out(["Geography"]))
geo_encoder_df

        Geography_France  Geography_Germany  Geography_Spain
0                    1.0                0.0              0.0
1                    1.0                0.0              0.0
2                    1.0                0.0              0.0
3                    1.0                0.0              0.0
4                    0.0                0.0              1.0
...                  ...                ...              ...
175027               1.0                0.0              0.0
175028               0.0                1.0              0.0
175029               0.0                1.0              0.0
175030               1.0                0.0              0.0
175031               1.0                0.0              0.0

[175032 rows x 3 columns]

In [12]:
# combine one hot data into original data
data=pd.concat([data.drop("Geography",axis=1),geo_encoder_df],axis=1)
data

,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,Okwudilichukwu,668,1,33,3,0.00,2,1.0,0.0,181449.97,0,1.0,0.0,0.0
1,Okwudiliolisa,627,1,33,1,0.00,2,1.0,1.0,49503.50,0,1.0,0.0,0.0
2,Hsueh,678,1,40,10,0.00,2,1.0,0.0,184866.69,0,1.0,0.0,0.0
3,Kao,581,1,34,2,148882.54,1,1.0,1.0,84560.88,0,1.0,0.0,0.0
4,Chiemenam,716,1,33,5,0.00,2,1.0,1.0,15068.83,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175027,Liu,709,0,36,7,0.00,1,0.0,1.0,42085.58,1,1.0,0.0,0.0
175028,Sabbatini,772,1,42,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
175029,Sabbatini,772,1,42,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
175030,Walker,792,0,28,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0
175031,Walker,792,0,28,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0

In [13]:
data=data.drop(['Surname'],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,668,1,33,3,0.00,2,1.0,0.0,181449.97,0,1.0,0.0,0.0
1,627,1,33,1,0.00,2,1.0,1.0,49503.50,0,1.0,0.0,0.0
2,678,1,40,10,0.00,2,1.0,0.0,184866.69,0,1.0,0.0,0.0
3,581,1,34,2,148882.54,1,1.0,1.0,84560.88,0,1.0,0.0,0.0
4,716,1,33,5,0.00,2,1.0,1.0,15068.83,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175027,709,0,36,7,0.00,1,0.0,1.0,42085.58,1,1.0,0.0,0.0
175028,772,1,42,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
175029,772,1,42,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0
175030,792,0,28,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0
175031,792,0,28,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0

In [14]:
# save onehot and label 
with open("label_encoder_gender.pkl","wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("onehot_geo.pkl","wb") as file:
    pickle.dump(onehot_geo,file)

In [15]:
# divide dataset into dependent and independent
X=data.drop(["Exited"],axis=1)
y=data["Exited"]

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
X_train

array([[ 1.20359521,  0.87920816, -0.68827208, ..., -1.14292038,
         1.92890808, -0.53381936],
       [-1.22586022, -1.13738708,  1.3206185 , ..., -1.14292038,
        -0.51842802,  1.87329287],
       [-0.30094064, -1.13738708, -0.01864189, ..., -1.14292038,
         1.92890808, -0.53381936],
       ...,
       [ 1.19126295, -1.13738708,  0.09296315, ...,  0.87495159,
        -0.51842802, -0.53381936],
       [ 0.3526692 , -1.13738708,  1.09740844, ...,  0.87495159,
        -0.51842802, -0.53381936],
       [ 0.1306885 ,  0.87920816, -0.35345698, ..., -1.14292038,
         1.92890808, -0.53381936]], shape=(140025, 12))

In [19]:
X_test

array([[ 0.75963381,  0.87920816,  0.20456818, ..., -1.14292038,
        -0.51842802,  1.87329287],
       [ 0.69797251, -1.13738708, -0.68827208, ...,  0.87495159,
        -0.51842802, -0.53381936],
       [ 0.31567242,  0.87920816, -0.68827208, ...,  0.87495159,
        -0.51842802, -0.53381936],
       ...,
       [ 0.72263703, -1.13738708,  0.87419837, ..., -1.14292038,
        -0.51842802,  1.87329287],
       [-0.18995029, -1.13738708, -0.79987711, ..., -1.14292038,
         1.92890808, -0.53381936],
       [-0.1529535 ,  0.87920816, -0.24185195, ..., -1.14292038,
        -0.51842802,  1.87329287]], shape=(35007, 12))

In [20]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

ANN IMPLEMENTATION

In [21]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [22]:
(X_train.shape[1])

12

In [23]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

d:\DL_project\venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [26]:
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=["accuracy"])

In [27]:
# set up tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y/%m/%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [28]:
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=5,restore_best_weights=True)

In [29]:
# train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
    
)

Epoch 1/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.8576 - loss: 0.3397 - val_accuracy: 0.8595 - val_loss: 0.3360
Epoch 2/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.8613 - loss: 0.3316 - val_accuracy: 0.8603 - val_loss: 0.3344
Epoch 3/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.8624 - loss: 0.3299 - val_accuracy: 0.8606 - val_loss: 0.3329
Epoch 4/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.8626 - loss: 0.3290 - val_accuracy: 0.8616 - val_loss: 0.3314
Epoch 5/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8630 - loss: 0.3287 - val_accuracy: 0.8609 - val_loss: 0.3324
Epoch 6/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8631 - loss: 0.3282 - val_accuracy: 0.8608 - val_loss: 0.3325
Epoch 7/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8628 - loss: 0.3280 - val_accuracy: 0.8613 - val_loss: 0.3307
Epoch 8/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8631 - loss: 0.3278 - val_accuracy: 0.8629 - val_loss: 0.3307
Epoch 9/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.8630 - loss: 0.3276 - val_accuracy: 0.8615 - val_loss: 0.3309
Epoch 10/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 6s 1ms/step - accuracy: 0.8627 - loss: 0.3277 - val_accuracy: 0.8623 - val_loss: 0.3304
Epoch 11/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 1ms/step - accuracy: 0.8635 - loss: 0.3272 - val_accuracy: 0.8631 - val_loss: 0.3300
Epoch 12/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8635 - loss: 0.3271 - val_accuracy: 0.8635 - val_loss: 0.3285
Epoch 13/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.8635 - loss: 0.3268 - val_accuracy: 0.8629 - val_loss: 0.3288
Epoch 14/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - accuracy: 0.8636 - loss: 0.3268 - val_accuracy: 0.8623 - val_loss: 0.3293
Epoch 15/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - accuracy: 0.8634 - loss: 0.3267 - val_accuracy: 0.8636 - val_loss: 0.3305
Epoch 16/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8641 - loss: 0.3266 - val_accuracy: 0.8623 - val_loss: 0.3296
Epoch 17/100
4376/4376 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8634 - loss: 0.3266 - val_accuracy: 0.8629 - val_loss: 0.3298

In [30]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [31]:
# load tensorboard extension
%load_ext tensorboard

In [32]:

%tensorboard --logdir logs

Reusing TensorBoard on port 6007 (pid 29656), started 22:38:14 ago. (Use '!kill 29656' to kill it.)